export const allProduct = [
  {
    id: 1,
    categorys: "gift card",
    categoryId: 102,
    img: "/images/itunes.png",
    title: "itunes-gift-card",
    productTitle: "iTunes Gift Card",
    price: "300TK - 22000TK",
    discountPrice: "280TK - 20000TK",
    stock: 60,
    product: ["$5", "$10", "$25", "$50", "$100"],
    productPrice: ["580 TK", "1150 TK", "2850 TK", "5700 TK", "11400 TK"],
    bgimg: "/images/bg-itunes.jpg",
    description: "Buy iTunes Gift Cards to enjoy apps, music, movies, and subscriptions on Apple devices.",
    review: { rating: 4.5, totalReviews: 120, comments: [{ user: "Ali", comment: "Fast delivery and authentic codes!" }, { user: "Sara", comment: "Good customer service and price." }] },
    
  },
  {
    id: 2,
    categorys: "gift card",
    categoryId: 102,
    img: "/images/playstation.png",
    title: "playstation-gift-card",
    productTitle: "PlayStation Gift Card",
    price: "500TK - 2364TK",
    discountPrice: "450TK - 2100TK",
    stock: 70,
    product: ["$10", "$20", "$25","$50", "$100"],
    productPrice: ["950 TK", "1850 TK", "2170 TK","4650 TK", "9300 TK"],
    bgimg: "/images/bg-playstation.jpg",
    description: "PlayStation Gift Cards let you buy games, add-ons, and subscriptions from the PlayStation Store.",
    review: { rating: 4.7, totalReviews: 85, comments: [{ user: "Rafi", comment: "Worked instantly, no issues." }, { user: "Nisha", comment: "Very reliable seller!" }] },
   
  },
  {
    id: 3,
    categorys: "gift card",
    categoryId: 102,
    img: "/images/netflix.png",
    title: "netflix-account",
    productTitle: "Netflix Account",
    price: "600TK - 97989TK",
    discountPrice: "550TK - 90000TK",
    stock: 40,
    product: ["1 Month", "3 Months","6 Months", "12 Months"],
    productPrice: ["550 TK", "1600 TK","3000 TK", "5800 TK"],
    bgimg: "/images/bg-netflix.jpg",
    description: "Get access to unlimited movies, TV shows, and originals with a Netflix subscription.",
    review: { rating: 4.6, totalReviews: 95, comments: [{ user: "Hina", comment: "Account worked perfectly." }, { user: "Shuvo", comment: "Quick and easy setup." }] },

  },
  {
    id: 4,
    categorys: "gift card",
    categoryId: 102,
    img: "/images/visa.png",
    title: "visa-master-card",
    productTitle: "VISA / Master Card",
    price: "600TK - 78788TK",
    discountPrice: "580TK - 75000TK",
    stock: 55,
    product: ["$5", "$10", "$25", "$50", "$100"],
    productPrice: ["600 TK", "1150 TK", "2800 TK", "5600 TK", "11200 TK"],
    bgimg: "/images/bg-visa.jpg",
    description: "VISA / Master Cards can be used for global online shopping and subscriptions.",
    review: { rating: 4.4, totalReviews: 70, comments: [{ user: "Rana", comment: "Worked globally without issues." }, { user: "Tania", comment: "Good for online shopping." }] },
    
  },
  {
    id: 5,
    categorys: "gift card",
    categoryId: 102,
    img: "/images/Stream.png",
    title: "steam-gift-card",
    productTitle: "Steam Gift Card",
    price: "600TK - 78788TK",
    discountPrice: "570TK - 75000TK",
    stock: 100,
    product: ["$5", "$10", "$20", "$50", "$100"],
    productPrice: ["580 TK", "1150 TK", "2200 TK", "5600 TK", "11200 TK"],
    bgimg: "/images/bg-steam.jpg",
    description: "Steam Gift Cards are perfect for buying PC games, DLCs, and wallet balance.",
    review: { rating: 4.8, totalReviews: 140, comments: [{ user: "Arif", comment: "Instant code delivery!" }, { user: "Maya", comment: "Very helpful support." }] },
    
  },
  {
    id: 6,
    categorys: "gift card",
    categoryId: 102,
    img: "/images/Amazon.png",
    title: "amazon-gift-card",
    productTitle: "Amazon Gift Card",
    price: "600TK - 78788TK",
    discountPrice: "580TK - 76000TK",
    stock: 130,
    product: ["$5", "$10", "$25", "$50", "$100"],
    productPrice: ["600 TK", "1150 TK", "2850 TK", "5700 TK", "11400 TK"],
    bgimg: "/images/bg-amazon.jpg",
    description: "Amazon Gift Cards let you shop millions of items including books, gadgets, and more.",
    review: { rating: 4.7, totalReviews: 180, comments: [{ user: "Rifat", comment: "Quick delivery, easy to redeem." }, { user: "Sadia", comment: "Very useful gift." }] },
   
  },
  {
    id: 8,
    categorys: "games to up",
    categoryId: 101,
    img: "/images/uc.png",
    title: "pubg-mobile-uc",
    productTitle: "Pubg Mobile UC",
    price: "100TK - 10000TK",
    discountPrice: "90TK - 9500TK",
    stock: 120,
    product: ['60 UC', '120 UC', '180 UC', '325 UC', '385 UC'],
    productPrice: ['115 TK', '258 TK', '350 TK', '575 TK', '690 TK'],
    bgimg: "/images/product-uc.png",
    description: "Top up PUBG Mobile UC instantly and buy skins, outfits, and battle passes.",
    review: { rating: 4.8, totalReviews: 200, comments: [{ user: "Tanvir", comment: "Super fast top-up!" }, { user: "Mina", comment: "Exactly what I needed." }] },
    
  },
  {
    id: 9,
    categorys: "games to up",
    categoryId: 101,
    img: "/images/cp.png",
    title: "call-of-duty-cp",
    productTitle: "Call Of Duty CP",
    price: "200TK - 11000TK",
    discountPrice: "180TK - 10000TK",
    stock: 95,
    product: ["80 CP", "160 CP", "420 CP", "880 CP", "2400 CP", "5000 CP"],
    productPrice: ["150 TK", "280 TK", "720 TK", "1250 TK", "3250 TK", "6500 TK"],
    bgimg: "/images/bg-duty.jpg",
    description: "Recharge COD Mobile CP to unlock weapons, skins, and premium battle passes.",
    review: { rating: 4.6, totalReviews: 150, comments: [{ user: "Shakib", comment: "Fast and reliable!" }, { user: "Nabila", comment: "No issues with top-up." }] },

  },
  {
    id: 10,
    categorys: "games to up",
    categoryId: 101,
    img: "/images/clash-of-clan.png",
    title: "clash-of-clan",
    productTitle: "Clash Of Clan",
    price: "600TK - 53577TK",
    discountPrice: "550TK - 50000TK",
    stock: 85,
    product: ["500 Gems", "1200 Gems", "2500 Gems", "6500 Gems", "14000 Gems"],
    productPrice: ["550 TK", "1200 TK", "2400 TK", "6200 TK", "13500 TK"],
    bgimg: "/images/bg-clan.jpg",
    description: "Purchase Clash of Clans Gems to build faster and upgrade your village.",
    review: { rating: 4.7, totalReviews: 110, comments: [{ user: "Joy", comment: "Smooth and fast." }, { user: "Mili", comment: "Exactly what I needed." }] },
    
  },
  {
    id: 11,
    categorys: "games to up",
    categoryId: 101,
    img: "/images/Genshin-Impact.png",
    title: "genshin-impact",
    productTitle: "Genshin Impact",
    price: "600TK - 78788TK",
    discountPrice: "570TK - 75000TK",
    stock: 90,
    product: ["60 Crystals", "300 Crystals", "980 Crystals", "1980 Crystals", "3280 Crystals", "6480 Crystals"],
    productPrice: ["600 TK", "1800 TK", "5200 TK", "10500 TK", "17500 TK", "34000 TK"],
    bgimg: "/images/bg-genshin.jpg",
    description: "Recharge Genesis Crystals in Genshin Impact to buy Primogems and character skins.",
    review: { rating: 4.9, totalReviews: 220, comments: [{ user: "Rafiq", comment: "Instant delivery, very happy." }, { user: "Sara", comment: "Great service!" }] },
   
  },
  {
    id: 12,
    categorys: "games to up",
    categoryId: 101,
    img: "/images/FIFA-Mobile.png",
    title: "fifa-mobile",
    productTitle: "FIFA Mobile",
    price: "600TK - 78788TK",
    discountPrice: "550TK - 74000TK",
    stock: 65,
    product: ["500 FIFA Points", "1050 FIFA Points", "2200 FIFA Points", "5750 FIFA Points", "12000 FIFA Points"],
    productPrice: ["600 TK", "1150 TK", "2300 TK", "5800 TK", "11800 TK"],
    bgimg: "/images/bg-fifa.jpg",
    description: "Buy FIFA Mobile Points to build your dream squad and unlock premium rewards.",
    review: { rating: 4.7, totalReviews: 130, comments: [{ user: "Tanzim", comment: "Quick and safe top-up." }, { user: "Maya", comment: "Perfect for my team." }] },
  
  },
  {
    id: 13,
    categorys: "games to up",
    categoryId: 102,
    img: "/images/brawl-Stars.png",
    title: "brawl-stars",
    productTitle: "Brawl Stars",
    price: "600TK - 78788TK",
    discountPrice: "580TK - 75000TK",
    stock: 55,
    product: ["80 Gems", "170 Gems", "360 Gems", "950 Gems", "2000 Gems"],
    productPrice: ["600 TK", "1150 TK", "2300 TK", "5800 TK", "11800 TK"],
    bgimg: "/images/bg-brawl.jpg",
    description: "Top up Brawl Stars Gems and unlock new brawlers, skins, and special offers.",
    review: { rating: 4.6, totalReviews: 90, comments: [{ user: "Shakil", comment: "Delivered instantly." }, { user: "Nabila", comment: "Good experience!" }] },

  },
  {
    id: 14,
    categorys: "games to up",
    categoryId: 102,
    img: "/images/Clash-Of-Royal.png",
    title: "clash-of-royal",
    productTitle: "Clash Of Royal",
    price: "600TK - 78788TK",
    discountPrice: "570TK - 75000TK",
    stock: 10,
    product: ["80 Gems", "170 Gems", "360 Gems", "950 Gems", "2000 Gems"],
    productPrice: ["600 TK", "1150 TK", "2300 TK", "5800 TK", "11800 TK"],
    bgimg: "/images/bg-royal.jpg",
    description: "Recharge Clash Royale Gems to upgrade cards, unlock chests, and buy exclusive items.",
    review: { rating: 4.5, totalReviews: 50, comments: [{ user: "Arman", comment: "Worked fine." }, { user: "Tania", comment: "Fast top-up." }] },
   
  },
  {
    id: 15,
    categorys: "games to up",
    categoryId: 102,
    img: "/images/Once-Human.png",
    title: "once-human",
    productTitle: "Once Human",
    price: "600TK - 78788TK",
    discountPrice: "580TK - 76000TK",
    stock: 130,
    product: ["60 Credits", "300 Credits", "980 Credits", "1980 Credits", "3280 Credits", "6480 Credits"],
    productPrice: ["600 TK", "1800 TK", "5200 TK", "10500 TK", "17500 TK", "34000 TK"],
    bgimg: "/images/bg-human.jpg",
    description: "Top up Once Human Credits to enhance gameplay and unlock premium features.",
    review: { rating: 4.8, totalReviews: 160, comments: [{ user: "Raihan", comment: "Very fast and reliable." }, { user: "Mina", comment: "Perfect top-up." }] },
    
  }
];
